# STEP 2 â†’ STEP 3 (biodata page)
[[redirects]]
  from = "/alliance/data"
  to = "/alliance/data/index.html"
  status = 200

# FINAL THANK YOU PAGE
[[redirects]]
  from = "/thank-you"
  to = "/thank-you.html"
  status = 200
